### ISSUE TITLE
Update README to Replace Cloud9 Deployment Instructions with SageMaker

### ISSUE THREAD

**Issue by yhayano-ponotech** [aws-samples/cost-effective-aws-deployment-of-comfyui#9]
The current deployment instructions in this repository's README use Cloud9, but as Cloud9 has been deprecated, we need to use SageMaker instead. Could you please update the README to include instructions for deploying using SageMaker?

**Comment by maekawataiki** [comment]
Thank you for bringing this up. 

I've updated the README with new instructions for deploying using Amazon SageMaker Studio Code Editor.

Please take a look at the updated README and let us know if you need any clarification or have additional feedback. We appreciate you taking the time to improve the project documentation.

**Comment by yhayano-ponotech** [comment]
@maekawataiki 
Thank you for the update. 

I followed the new instructions for SageMaker but encountered the following issues. Could you please check them?

- The output of `echo "export AWS_DEFAULT_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)"` seems to assign the account ID to `AWS_DEFAULT_ACCOUNT`, but when executing `echo $AWS_DEFAULT_ACCOUNT`, the output is empty and it appears not to be set.
    - For now, I directly edited `/etc/environment` to set `AWS_DEFAULT_ACCOUNT`.
- The command `echo "export AWS_DEFAULT_REGION=$(aws configure get region)"` does not set the default region because `aws configure get region` returns empty.
    - Should I set the default region with `aws configure set region us-west-2`?
- After a certain period of time, SageMaker shuts down.
    - The `AutoStopIdleTimeInMinutes` setting for `sagemaker-studio-code-editor-template` is set to 60 minutes, but this seems insufficient, so it might be better to change it to 120-180 minutes.
- When running `cdk bootstrap`, I encounter the error `bash: cdk: command not found`.
    - First, I executed `npm install -g aws-cdk` and confirmed it was installed.
    - After the error `bash: cdk: command not found` occurred with `cdk bootstrap`, I tried running `npm install -g aws-cdk`, but then I got `bash: npm: command not found`, indicating that the `npm` command is unavailable.

**Comment by maekawataiki** [comment]
@yhayano-ponotech  Thank you for the feedback.

For `AWS_DEFAULT_ACCOUNT` and `AWS_DEFAULT_REGION`, the updated command only prints command and user need to execute printed command which is not clearly stated. I've updated the doc so the value is set properly on first time.

For `AutoStopIdleTimeInMinutes`, the ideal duration depends on workload. We may change AutoStopIdleTimeInMinutes as Cfn parameter.

For `cdk not found` problem, the globally installed library initialized on instant restarts, so it needs to be installed every time runtime restart. I wasn't able to replicate `npm: command not found`, can you share steps to reproduce the problem?

**Comment by yhayano-ponotech** [comment]
@maekawataiki

Thank you for your support.

We are currently facing the following issues, and I would appreciate it if you could kindly check:

- The output of `aws configure get region` is still empty. Could it be that running `aws configure set region [region name]` is necessary?
- The `cdn deploy` process halts at 84/104. I have recorded the entire workflow, so please review the footage at your convenience. 
    - https://youtu.be/TZecCDCt6es

**Comment by kaitas** [comment]
Here is my case,

> aws ecr create-repository --repository-name comfyui --image-scanning-configuration scanOnPush=true

In 2:30, https://youtu.be/TZecCDCt6es?feature=shared&t=186

It breaks my console...
`
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:us-west-2:879381280413:repository/comfyui2",
        "registryId": "(879...userid)",
        "repositoryName": "comfyui2",
        "repositoryUri": "(879...userid).dkr.ecr.us-west-2.amazonaws.com/comfyui2",
        "createdAt": "2024-10-24T04:37:40.402000+00:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": true
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}

...skipping...

`
![image](https://github.com/user-attachments/assets/15a6e379-eead-4c51-a574-f9fc8acfca00)

![image](https://github.com/user-attachments/assets/a37e2982-5196-4af7-9ca7-9f03be051a73)

**Comment by yhayano-ponotech** [comment]
@maekawataiki 
I increased the EbsSizeInGb when launching the SageMaker template. After that, the cdk deploy no longer got stuck at 84/104. However, the following error occurred.

```
ComfyUIStack: creating CloudFormation changeset...
3:33:26 AM | CREATE_FAILED        | AWS::ECS::Service                             | ComfyUIService6B91FEDA
Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: f3a5b98e-291f-ae33-5190-80dacd50cf42, HandlerErrorCode: GeneralService
Exception)

3:33:29 AM | DELETE_FAILED        | AWS::ECS::ClusterCapacityProviderAssociations | ComfyUICluster789D947D
Resource handler returned message: "The specified capacity provider is in use and cannot be removed. (Service: AmazonECS; Status Code: 400; Error Code: ResourceInUseException; Request ID: 04c42d87-83e4-
4c38-9270-a2b8c096863c; Proxy: null)" (RequestToken: 6d7370db-b516-1713-0c07-531a07d14678, HandlerErrorCode: null)

3:34:37 AM | DELETE_FAILED        | AWS::CloudFormation::CustomResource           | SelfSignedCertCustomResource
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (ResourceInUseException) when calling the DeleteCertificate operation: Certificate arn:aws:acm:us-west-
2:296062558999:certificate/e2f816fd-7845-4696-ab98-db54cebdd05f in account 296062558999 is in use.

Logs: /aws/lambda/ComfyUIStack-RegisterSelfSignedCertCF8717EB-ahnDLExlfZWz

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
❌  ComfyUIStack failed: The stack named ComfyUIStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following resource(s) failed to delete: [ComfyUICluster789D947D, SelfSignedCertCustomResource]. ): Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: f3a5b98e-291f-ae33-5190-80dacd50cf42, HandlerErrorCode: GeneralServiceException), Resource handler returned message: "The specified capacity provider is in use and cannot be removed. (Service: AmazonECS; Status Code: 400; Error Code: ResourceInUseException; Request ID: 04c42d87-83e4-4c38-9270-a2b8c096863c; Proxy: null)" (RequestToken: 6d7370db-b516-1713-0c07-531a07d14678, HandlerErrorCode: null), Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (ResourceInUseException) when calling the DeleteCertificate operation: Certificate arn:aws:acm:us-west-2:296062558999:certificate/e2f816fd-7845-4696-ab98-db54cebdd05f in account 296062558999 is in use.

Logs: /aws/lambda/ComfyUIStack-RegisterSelfSignedCertCF8717EB-ahnDLExlfZWz

    at invokeUserFunction (/var/task/framework.js:2:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: 508d1373-f189-4259-91e4-a336e13ae016)
```

**Comment by maekawataiki** [comment]
> Reason: No Container Instances were found in your capacity provider. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.

It seems underlying ASG has some problem. Can you check ASG events and share detail? 

> ECS Deployment Circuit Breaker was triggered'." (RequestToken: f3a5b98e-291f-ae33-5190-80dacd50cf42, HandlerErrorCode: GeneralService
Exception)

This is due to circuit breaker I recently added and reverted in #19. Can you pull latest version and see first error persists?

**Comment by yhayano-ponotech** [comment]
@maekawataiki 

The README has been updated, and I encountered the following error while following the updated README instructions. Could you please check it?

```
sagemaker-user@default:~/cost-effective-aws-deployment-of-comfyui$ cdk bootstrap
`cdk synth` may hang in Docker on Linux 5.6-5.10. See https://github.com/aws/aws-cdk/issues/21379 for workarounds.
[WARNING] aws-cdk-lib.aws_ec2.InstanceProps#keyName is deprecated.
  - Use `keyPair` instead - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#using-an-existing-ec2-key-pair
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_ec2.InstanceProps#keyName is deprecated.
  - Use `keyPair` instead - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#using-an-existing-ec2-key-pair
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_autoscaling.StepScalingActionProps#cooldown is deprecated.
  cooldown is not valid with step scaling action
  This API will be removed in the next major release.
Traceback (most recent call last):
  File "/home/sagemaker-user/cost-effective-aws-deployment-of-comfyui/app.py", line 10, in <module>
    comfy_ui_stack = ComfyUIStack(
                     ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagemaker-user/cost-effective-aws-deployment-of-comfyui/comfyui_aws_stack/comfyui_aws_stack.py", line 338, in __init__
    docker_image_asset = ecr_assets.DockerImageAsset(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/aws_cdk/aws_ecr_assets/__init__.py", line 415, in __init__
    props = DockerImageAssetProps(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/aws_cdk/aws_ecr_assets/__init__.py", line 1204, in __init__
    check_type(argname="argument network_mode", value=network_mode, expected_type=type_hints["network_mode"])
  File "/opt/conda/lib/python3.11/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/opt/conda/lib/python3.11/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument network_mode must be one of (aws_cdk.aws_ecr_assets.NetworkMode, NoneType); got str instead
Subprocess exited with error 1
```

**Comment by maekawataiki** [comment]
> Reason: No Container Instances were found in your capacity provider. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.

The issue was due to missing quota for G instances. Updated doc.
